### ISSUE TITLE
One Time USDC Deposit Feature

### ISSUE THREAD

**Issue by mkkmail** [Kwenta/kwenta#1185]
### Feature Proposal
1- Improvement USDC Deposit : 
For More easier trading in futures in the shortest possible time (considering the fluctuations of the market), it seems is better to make a one-time deposit USDC token. The need to Withdrawal and re-deposit the USDC to trade any currency takes the trader's time and is not a good user experience.

2- menu in responsive view
for better UI/UX menu icon and start trading button should be in the header.

![Screen-Shot-1401-04-29-at-17 25 37](https://user-images.githubusercontent.com/8843747/181182456-d718a831-6115-490f-b676-5b163c55bb57.jpg)

**Comment by platschi** [comment]
Thanks for your feature proposal! Answering your comments below:
> 1- Improvement USDC Deposit :

Kwenta uses sUSD for trading Perps. I believe what you mean is cross-margin, which we are actively working on in order to allow a one-time deposit that allows users to trade in different markets.

> 2- menu in responsive view
Thanks, noted and forwarded to our designer for consideration!
