### ISSUE TITLE
Twitter metadata incompatibility 

### ISSUE THREAD

**Issue by Marko-roy** [Kwenta/kwenta#26]
## **_Summary_**

Twitter currently does not show our image card when we post the Kwenta.io link on their platform.

## **_Your environment_**

Twitter/ any medium that's applicable 

## **_Expected behaviour_**

Posting kwenta.io hyperlink on twitter should pull metadata to display a website card with our image when posted.Most websites already do this, see image below.

<img src="https://user-images.githubusercontent.com/90076964/132411043-726f591a-42fd-45d9-b45c-6dbf8655a9a6.jpg" width="350" height="262">

## **_Actual behavior_**

Currently does not display a website card.

<img src="https://user-images.githubusercontent.com/90076964/132412194-f042270f-ea93-4c99-b9aa-4957ce42bd9e.jpg" width="350" height="262">

## **_Steps to reproduce_**

  1. Grab the https://kwenta.io
  2. Post link in a tweet
  3. No image will be displayed

**Comment by platschi** [comment]
It looks like a caching issue and Twitterbot is not re-fetching the image, because the metadata looks just fine:

https://github.com/Kwenta/kwenta/blob/ce22aba72e48982c3df2a921b0574b35242a787b/pages/_app.tsx#L77-L82

A [simple workaround](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/troubleshooting-cards#refreshing_images
) is to add an extra parameter to the end of the image URL to trigger Twitterbot to re-fetch it.
Once done, the card can be verified [here](https://cards-dev.twitter.com/validator).
