### ISSUE TITLE
Withdraws marked as liquidations in Trade History

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#843]
### Subject of the issue
`WithdrawAllMargin` txs are considered liquidations by the current implementation of #833. 

It is probably desired to not treat margin withdrawals als "trades" or "liquidations" ? Would need to double check also with Trade History if those are added there or not.

![Screen Shot 2022-05-13 at 09 48 10](https://user-images.githubusercontent.com/548702/168294326-918ad2ba-049b-4289-9b76-156d320eed54.png)

Txs in screenshot: 

[1](https://optimistic.etherscan.io/tx/0xa2382c6ebb1b75977f9186c1f535c0805715373e7eb9c921499062622a9c580f), [2](https://optimistic.etherscan.io/tx/0x0a3ffc123050643122a5c2f161b7a3ae26564f47d4cce3b6a048dce97959433c)

**Comment by brossetti1** [comment]
@platschi spoke with @koredefashokun - the fix here is non impactful and only adds a new conditional check that a `withdrawalAll` does not trigger this liquidation creation (the conditional also applies to deposits but shouldnt matter).

this should fix the issue with only marking trade entities that are actually liquidations correctly. Just noticed this issue is still open, might be able to close it with this current issue

https://github.com/Kwenta/kwenta/issues/813
