### ISSUE TITLE
Optimistic Kovan markets not working on Kwenta

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#856]
### Subject of the issue
Recent synthetix updates might have broken Optimistic Kovan on v2.  

No markets are shown on the dashboard when connected.

<img width="1823" alt="Screen Shot 2022-05-18 at 16 36 08" src="https://user-images.githubusercontent.com/548702/169141845-c03f3391-cc19-4382-8f4d-cd70c6ca1812.png">

### Steps to reproduce
- Connect your wallet to v2
- Switch network to Optimistic Kovan
- No markets available

**Comment by LeifuChen** [comment]
@raffiegang 
I compared the deployed contract `FuturesMarketData` between `optimism-kovan` and `optimism`.
- [optimism-kovan](https://kovan-optimistic.etherscan.io/address/0x92CA72696B15b0F0C239E838148495016950af51#readContract)
![image](https://user-images.githubusercontent.com/4819006/169158571-edbcbb49-b201-4a04-a133-447c74f87c3d.png)
- [optimism](https://optimistic.etherscan.io/address/0xC51aeDBEC3aCD26650a7E85B6909E8AEc4d0F19e#readContract)
![image](https://user-images.githubusercontent.com/4819006/169158664-eef7a50f-543b-4650-a34e-9887b876eeeb.png)

**Comment by LeifuChen** [comment]
@platschi The issue has been resolved.
![image](https://user-images.githubusercontent.com/4819006/169287196-d0472433-9e21-4759-8f3a-66d5f1837d60.png)

The root cause is the code reverting from snx side.
![image](https://user-images.githubusercontent.com/4819006/169287101-521cdfa4-6bc3-40d0-b46a-0fcd693f6177.png)

**Comment by platschi** [comment]
Awesome!
