### ISSUE TITLE
uPnL calculation wrong on PositionCard

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#868]
Users reporting that the uPnL calculation is off after modifying a position. See current position on Op Kovan, Kwenta wallet:

<img width="721" alt="Screen_Shot_2022-05-23_at_9 08 42_AM" src="https://user-images.githubusercontent.com/548702/169847849-43b6e4cf-cb28-42c4-86f0-5b014404af43.png">

Note: Calculation is correct, but labels are misleading as it calculates based on last entry, not avg entry. Consider adding this info to tooltip or change the label text for "Avg Entry".

**Comment by Tburm** [comment]
Update - spoke with Marko and the calculation is working as expected. We can not calculate unrealized pnl based on avg price because the realized pnl take every modification into account. If we use avg price to calculate pnl we will end up double-counting some profits.

Unrealized pnl should be based off of "last price" meaning price during last modification (margin transfer or position size). This is how it works today. To make this more clear we should consider displaying "Last price" and killing "Avg. Entry" on this position card.

**Comment by Tburm** [comment]
We decided to switch unrealized pnl with liquidation price.
